#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function help {
echo <<EOF
usage: $0 [options]

This installs all files necessary to use these dotfiles, including symlinking
the files correctly.

OPTIONS:
  -h    Show this help messgae.
  -r    Uninstall.
EOF
}

REMOVE=false
YES=false
while getopts "rh" OPTION
do
    case $OPTION in
        r)
            REMOVE=true;;
        h)
            help;;
    esac
done

## FUNCTIONS
function link {
    read -p "Do you want to link ~/.$1 to ${DIR}/files/$1? "
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        ln -s ${DIR}/files/$1 ~/.$1
    fi
}

function remove {
    read -p "Do you want to remove ~/.$1 (if linked to ${DIR}/files/$1)? "
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        if [[ $(readlink ~/.$1) == "${DIR}/files/$1" ]]
        then
            rm -f ~/.$1
        else
            echo "~/.$1 not linked to ${DIR}/files/$1 (but to $(readlink ~/.$1)"
        fi
    fi
}

## MAIN
# REMOVE
if $REMOVE
then
    for file in ${DIR}/files/*; do
        remove $(basename $file)
    done

    exit 1
fi

# LINK
#read -p "Do you want to install the Powerline font patches (Linux only)? "
#if [[ $REPLY =~ ^[Yy]$ ]]
#then
#    FONTURI=https://github.com/Lokaltog/powerline/raw/develop/font/
#    wget ${FONTURI}PowerlineSymbols.otf \
#        -O ~/.fonts/PowerlineSymbols.otf
#    if [ -d "~/.fonts.conf.d/" ]
#    then
#        DEST="~/.fonts.conf.d/"
#    elif [ -d "~/.config/fontconfig/conf.d/" ]
#    then
#        DEST="~/.config/fontconfig/conf.d/"
#    else
#        DEFAULT="$(echo ~)/.config/fontconfig/conf.d/"
#        read -p "Where should I put 10-powerline-symbols.conf? [${DEFAULT}] "
#        if [[ $REPLY == "" ]]
#        then
#            DEST=$DEFAULT
#        else
#            DEST=$REPLY
#        fi
#    fi
#    if [ ! -d $DEST ]
#    then
#        mkdir --parents $DEST
#    fi
#    wget ${FONTURI}10-powerline-symbols.conf \
#        -O ${DEST}10-powerline-symbols.conf
#
#    echo "You may need to restart your terminal emulator (or even X) before" \
#         " this works"
#fi

for file in ${DIR}/files/*; do
    link $(basename $file)
done

read -p "Do you want to install Vim plugins with Plug? "
if [[ $REPLY =~ ^[Yy]$ ]]
then
    vim +PlugInstall
fi
