#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function help {
echo <<EOF
usage: $0 [options]

This installs all files necessary to use these dotfiles. It creates symlinks to
all files in the links/ directory and copies the files from the templates/
directory. It also replaces any occurrence of {{dotfiles}} in the templates by
the path to the dotfiles repository (so if you're moving it around, reinstall).

OPTIONS:
  -h    Show this help messgae.
  -r    Uninstall.
EOF
}

REMOVE=false
YES=false
while getopts "rh" OPTION
do
    case $OPTION in
        r)
            REMOVE=true;;
        h)
            help;;
    esac
done

## FUNCTIONS
function link {
    read -p "Do you want to link ~/.$1 to ${DIR}/files/$1? [y/N] "
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        if [[ -L ~/.$1 ]];  then
            echo "Symlink already present"
        else
            ln -s ${DIR}/links/$1 ~/.$1
        fi
    fi
}
function copy {
    read -p "Do you want to copy ${DIR}/files/$1 to ~/.$1? [y/N] "
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        cp ${DIR}/templates/$1 ~/.$1
        sed -i "s/{{dotfiles}}/$(echo $DIR | sed -e 's/[\/&]/\\&/g')/g" ~/.$1
    fi
}


# Removes all installed links
function remove_link {
    if [[ $(readlink ~/.$1) == "${DIR}/links/$1" ]]; then
        read -p "Do you want to remove ~/.$1? [y/N] "
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -f ~/.$1
        fi
    fi
}


## MAIN
function main {
    # REMOVE
    if $REMOVE; then
        for file in ${DIR}/links/*; do
            remove_link $(basename $file)
        done

        exit 1
    fi

    # LINK/COPY
    for file in ${DIR}/links/*; do
        link $(basename $file)
    done
    for file in ${DIR}/templates/*; do
        copy $(basename $file)
    done

    # PLUG INSTALL
    read -p "Do you want to install Vim plugins with Plug? [y/N] "
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        vim +PlugInstall
    fi
}
main
