#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

source ~/.bash/git-prompt
source ~/.bash/colors

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vi='vim'
alias pacman='pacman-color'
alias sudo='sudo '
PS1="[${C_EMW}\@ ${C_Y}\u@\h${C_N} \w${C_Y}\$(__git_ps1 \" (%s)\")${C_N}]${C_G}\$ ${C_N}"
