" vimrc
set nocompatible               " be iMproved
filetype off                   " required!

" Plug!
call plug#begin('~/.vim/plugged')
Plug 'bling/vim-airline'
Plug 'airblade/vim-gitgutter'
Plug 'vim-scripts/Zenburn'
Plug 'pthrasher/conqueterm-vim'
Plug 'scrooloose/nerdtree'
Plug 'davidhalter/jedi-vim'
Plug 'ervandew/supertab'
call plug#end()


"" Some basic configuration
filetype plugin indent on
set encoding=utf-8
syntax on
set t_Co=256
colorscheme zenburn

"" Functional settings
set hidden         " Hide buffers, don't close them.
set number         " Line numbers plz.
set showmatch      " Matching parenthesis.
set backspace=eol,start " Backspace!
set title          " Window title overwrite.
set wildignore=*.swp,*.bak,*.pyc,*.class
                   " Ignore stupid files.
set scrolloff=3    " Show three lines below the cursor.

"" Grouped settings
" Visible whitespace characters
set list
set listchars=tab:»\ ,trail:·,extends:…,eol:¶

" Less annoyances
set visualbell
set noerrorbells

if v:version >= 703
  " Colored area after 80th character
  hi ColorColumn ctermbg=238
  let &colorcolumn=join(range(81,999),",")
endif

" Better history/undo
set history=1000
set undolevels=1000

" No mess
set nobackup
set noswapfile

" Better indentation
set expandtab
set tabstop=4
set autoindent
set copyindent
set shiftwidth=4
set smarttab
set shiftround

" Better searching
set ignorecase
set smartcase
set hlsearch

"" (Re)maps
" ; is way better than :
map ; :
noremap ;; ;

" , is a better leader than \
let mapleader=","

" Pasting? Press F2 first!
set pastetoggle=<F2>

" No arrow keys.
map <Up> <NOP>
map <Down> <NOP>
map <Left> <NOP>
map <Right> <NOP>

" But Ctrl+Arrow switches between tabs!
nnoremap <silent> <C-k> :new<CR>
nnoremap <silent> <C-j> :bd<CR>
nnoremap <silent> <C-h> :bp<CR>
nnoremap <silent> <C-l> :bn<CR>

" Clear searches with ,/
nmap <silent> ,/ :nohlsearch<CR>

" ,ev and ,sv to edit and reload .vimrc
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" Reselect visual block after indent/outdent.
vnoremap < <gv
vnoremap > >gv

"" Plugins
" Airline
set laststatus=2
" Disable fancy symbols by default.
"let g:Powerline_symbols = 'fancy'
let g:airline#extensions#tabline#enabled = 1

if filereadable("~/.vim_custom")
    source ~/.vim_custom
endif

" GitGutter
highlight clear SignColumn

" MiniBufExpl
let g:miniBufExplMapWindowNavVim = 1 
let g:miniBufExplMapWindowNavArrows = 1 
let g:miniBufExplMapCTabSwitchBufs = 1 
let g:miniBufExplModSelTarget = 1 

" NERDTree
autocmd vimenter * NERDTree
autocmd VimEnter * wincmd p

map <C-n> :NERDTreeToggle<CR>

" Jedi
let g:jedi#use_tabs_not_buffers = 0
