autoload -U compinit && compinit
zmodload -i zsh/complist
autoload -U promptinit && promptinit

fpath=(/usr/local/share/zsh-completions $fpath)
source ~/zsh/zsh-git-prompt/zshrc.sh

# an example prompt
PROMPT='%B%m%~%b$(git_super_status) %# '

export HISTFILE=~/.zsh_history
export SAVEHIST=1000
export HISTSIZE=1000
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY

# Fix python crash with vim and YCM plugin
export DYLD_FORCE_FLAT_NAMESPACE=1

export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
